#!/usr/bin/env python
"""Scheduled / on-demand daily run: build the meeting packet and email it as a PDF.

This is the ONE entry point the scheduler invokes and the same command you run by hand. It wraps the
existing, unchanged engine (calendar read -> per-meeting briefs -> packet markdown) and adds only a
delivery layer: render the packet to PDF and email it to a single recipient.

    python scheduled_run.py                 # today (Europe/Paris), email the PDF  (what cron runs)
    python scheduled_run.py --date 2026-06-29   # any day, on demand
    python scheduled_run.py --no-email          # build + save PDF locally, do NOT send
    python scheduled_run.py --to me@x.com       # one-off: override the recipient

Guarantees:
  * Headless: API-key model auth + Notion integration token + Google service account. No login.
  * Read-only everywhere except the email: the run ASSERTS zero writes to Notion and the calendar
    before sending; email is the only outbound action.
  * Never fails silently: on the emailing path, ANY failure (API/network/429-after-retries, calendar
    or render error, empty day, a detected write) sends a FAILURE notice with a short traceback and
    exits non-zero. With --no-email, the same failure is printed to the console and exits non-zero.

Exit codes: 0 success · 2 usage / missing credential (fail fast) · 1 any run failure.
"""

import argparse
import asyncio
import json
import os
import sys
import traceback
from datetime import date, datetime
from pathlib import Path
from zoneinfo import ZoneInfo

from brief_agent.agent import DEFAULT_MODEL
from brief_agent.calendar import fetch_day_events, parse_events
from brief_agent.config import (
    MissingAPIKeyError,
    MissingNotionTokenError,
    ensure_credentials,
)
from brief_agent.daily import render_packet, run_daily_briefing
from brief_agent.mailer import (
    MissingSMTPConfigError,
    load_email_config,
    send_email,
    send_failure_notice,
)
from brief_agent.pdf import render_packet_pdf

_TZ = ZoneInfo("Europe/Paris")


class PacketError(RuntimeError):
    """A packet-level failure worth alerting on (empty day, or a write was detected)."""


# --------------------------------------------------------------------------- #
# Day resolution + packet building (reuses the existing engine verbatim)
# --------------------------------------------------------------------------- #
def _resolve_day(spec: str | None) -> date:
    """`--date YYYY-MM-DD`, else today in Europe/Paris. Raises ValueError on a bad spec."""
    if not spec:
        return datetime.now(_TZ).date()
    return date.fromisoformat(spec.strip())


async def _build_packet(day: date, model: str, enable_web: bool):
    raw, fetch_calls = await fetch_day_events(day, model)
    events = parse_events(raw)
    return await run_daily_briefing(
        events, model=model, fetch_tool_calls=fetch_calls, enable_web=enable_web
    )


def _provenance(packet, day: date, model: str) -> dict:
    """Same combined sidecar the --calendar CLI writes: per-brief event id + Notion pages used."""
    return {
        "date": day.isoformat(),
        "model": model,
        "counts": {
            "total": packet.total,
            "briefed": packet.briefed,
            "unresolved": packet.stubs,
            "skipped": len(packet.skipped),
        },
        "items": [i.sources for i in packet.items],
        "skipped": [
            {"event_id": s.event_id, "status": "skipped", "title": s.title}
            for s in packet.skipped
        ],
    }


def _save_outputs(out_dir: Path, day: date, md: str, pdf_bytes: bytes, provenance: dict) -> dict:
    """Write day-<ISO>.{md,pdf,sources.json}. Deterministic names → idempotent, safe to re-run."""
    out_dir.mkdir(parents=True, exist_ok=True)
    stem = f"day-{day.isoformat()}"
    md_path = out_dir / f"{stem}.md"
    pdf_path = out_dir / f"{stem}.pdf"
    src_path = out_dir / f"{stem}.sources.json"
    md_path.write_text(md, encoding="utf-8")
    pdf_path.write_bytes(pdf_bytes)
    src_path.write_text(
        json.dumps(provenance, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    return {"md": md_path, "pdf": pdf_path, "sources": src_path}


def _email_body(packet, day: date, pdf_name: str) -> str:
    when = day.strftime("%A %d %B %Y")
    return (
        f"Meeting briefs for {when} are attached ({pdf_name}).\n\n"
        f"{packet.total} meetings - {packet.briefed} briefed / {packet.stubs} unresolved / "
        f"{len(packet.skipped)} skipped (internal).\n\n"
        "Read-only run: 0 writes to Notion and the calendar. Generated by the meeting-brief agent.\n"
    )


def _short_traceback(limit: int = 2000) -> str:
    tb = traceback.format_exc()
    return tb if len(tb) <= limit else "...\n" + tb[-limit:]


# --------------------------------------------------------------------------- #
# Run
# --------------------------------------------------------------------------- #
def _run(args) -> int:
    emailing = not args.no_email
    day = args.day  # already resolved + validated in main()
    out_dir = Path(args.out_dir)

    # On the emailing path, resolve SMTP config UP FRONT: fail fast if it's missing (we could not
    # send a failure notice anyway), and keep `cfg` ready for the failure path below.
    cfg = None
    if emailing:
        try:
            cfg = load_email_config(args.to)
        except MissingSMTPConfigError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 2

    print(
        f"Building the meeting packet for {day.isoformat()} (Europe/Paris) using model "
        f"'{args.model}'{'' if args.no_web else ' (+ web news)'}…",
        file=sys.stderr,
    )

    try:
        packet = asyncio.run(_build_packet(day, args.model, enable_web=not args.no_web))

        # Read-only gate: any write tool seen anywhere in the run is a hard failure.
        if packet.made_any_write:
            raise PacketError(
                f"write tool(s) were called — {sorted(set(packet.write_tool_calls))}"
            )
        # An empty day is treated as a failure so it never passes silently.
        if packet.total == 0:
            raise PacketError(f"no meetings found for {day.isoformat()} (empty day)")

        md = render_packet(packet)
        pdf_name = f"meeting-briefs-{day.isoformat()}.pdf"
        pdf_bytes = render_packet_pdf(md, title=f"Meeting briefs - {day.isoformat()}")
        paths = _save_outputs(out_dir, day, md, pdf_bytes, _provenance(packet, day, args.model))

        print(
            f"Packet: {packet.total} meetings · {packet.briefed} briefed / {packet.stubs} "
            f"unresolved / {len(packet.skipped)} skipped. Saved {paths['pdf']} "
            f"({len(pdf_bytes)} bytes) + {paths['md'].name} + {paths['sources'].name}.",
            file=sys.stderr,
        )

        if emailing:
            subject = f"Meeting briefs — {day.strftime('%A %d %B %Y')}"
            send_email(cfg, subject, _email_body(packet, day, pdf_name), [(pdf_name, pdf_bytes)])
            print(f"Emailed PDF to {cfg.recipient} (subject: {subject!r}).", file=sys.stderr)
        else:
            print("--no-email: saved locally, send skipped.", file=sys.stderr)

        print("Writes: 0 to Notion and Calendar (read-only).", file=sys.stderr)
        return 0

    except Exception as exc:  # noqa: BLE001 - the whole run is wrapped so it never fails silently
        summary = f"{type(exc).__name__}: {exc}"
        short_tb = _short_traceback()
        print(f"error: {summary}", file=sys.stderr)

        if emailing and cfg is not None:
            subject = f"Meeting briefs — FAILED — {day.isoformat()}"
            try:
                send_failure_notice(cfg, subject, summary, short_tb)
                print(f"Sent failure notice to {cfg.recipient}.", file=sys.stderr)
            except Exception as mail_exc:  # noqa: BLE001
                print(
                    f"ALSO could not send the failure email: "
                    f"{type(mail_exc).__name__}: {mail_exc}",
                    file=sys.stderr,
                )
        else:
            # --no-email: no failure email; surface the traceback to the console.
            print(short_tb, file=sys.stderr)
        return 1


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="scheduled_run",
        description="Build the day's meeting packet and email it as a PDF (scheduled or on demand).",
    )
    p.add_argument("--date", default=None, help="YYYY-MM-DD (default: today, Europe/Paris).")
    p.add_argument("--no-email", action="store_true",
                   help="Build + save the PDF locally; do not send. Errors go to the console.")
    p.add_argument("--to", default=None, help="Override the recipient for a one-off send.")
    p.add_argument("--no-web", action="store_true", help="Disable web enrichment (faster; for testing).")
    p.add_argument("--out-dir", default="out", help="Where to save the PDF/MD/sidecar (default: out/).")
    p.add_argument("--model", "-m", default=os.environ.get("BRIEF_AGENT_MODEL", DEFAULT_MODEL),
                   help='Model alias ("opus", "sonnet") or full ID (default: opus).')
    p.add_argument("--once", action="store_true",
                   help="Run immediately (the default behaviour; accepted for the test command).")
    return p


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)

    # Fail fast on missing model/CRM credentials (no fallback, no interactive login).
    try:
        ensure_credentials()
    except (MissingAPIKeyError, MissingNotionTokenError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    try:
        args.day = _resolve_day(args.date)
    except ValueError:
        print(f"error: bad --date {args.date!r} (use YYYY-MM-DD).", file=sys.stderr)
        return 2

    return _run(args)


if __name__ == "__main__":
    raise SystemExit(main())
